apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent
  namespace: jenkins
spec:
  selector:
    app: jenkins-agent
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
  type: ClusterIP