jenkins:
  clouds:
    - kubernetes:
        name: "kubernetes"
        serverUrl: "https://kubernetes.default"
        skipTlsVerify: true
        namespace: "jenkins"
        jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
        jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
        podLabels:
          - key: "jenkins/agent"
            value: "true"
        containerTemplate:
          name: "jnlp"
          image: "jenkins-agent:latest"
          alwaysPullImage: false
          workingDir: "/home/jenkins/agent"
          ttyEnabled: true
          resourceRequestCpu: "500m"
          resourceLimitCpu: "1000m"
          resourceRequestMemory: "1Gi"
          resourceLimitMemory: "2Gi"