controller:
  adminUser: "admin"
  adminPassword: "admin123"
  ingress:
    enabled: true
    hostName: jenkins.cluster.local
  installPlugins:
    - kubernetes:3.12.0
    - workflow-aggregator:2.7
    - git:4.11.5
    - docker-workflow:1.29
    - configuration-as-code:1.55
    - sonar:2.14
    - kubernetes-cli:1.10.3
    - docker-plugin:1.2.9
  additionalPlugins:
    - github:1.34.3
    - pipeline-utility-steps:2.13.0
    - credentials-binding:523.vd859a_4b_122e6
    - pipeline-stage-view:2.24

persistence:
  enabled: true
  size: 10Gi

serviceAccount:
  create: true
  name: jenkins
  annotations:
    kubernetes.io/cluster-role: cluster-admin